### ISSUE TITLE
Running project on Windows? Invalid bind mount

### ISSUE THREAD

**Issue by Marooned-MB** [laradock/laradock#498] opened 2016-12-20 13:19 UTC
When trying to run nginx I get this error:

```
$ docker-compose up -d nginx
Creating laradock_applications_1

ERROR: for applications  Cannot create container for service applications: Invalid bind mount spec "C:\\some\\windows\\path:/var/www:rw": Invalid volume specification: 'C:\some\windows\path:/var/www:rw'
←[31mERROR←[0m: Encountered errors while bringing up the project.
```

I've read `COMPOSE_CONVERT_WINDOWS_PATHS=1` in .env might help but it did not.
[Here](https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/1775) is mentioned that it might be due to colon in the path but that's default config for volume `- ../:/var/www` so hard to adjust that.

**Comment by sudden-break** [comment] 2016-12-20 13:28
#497

**Comment by philtrep** [comment] 2016-12-20 16:06
Closing this as a duplicate of #497. Please contribute to the original issue.

**Closed by philtrep** 2016-12-20 16:06 UTC
Labels: Duplicate
