### ISSUE TITLE
mysql container immediately exited (1)

### ISSUE THREAD

**Issue by tutanhamon326** [LaraDock/laradock#237] opened 2016-08-16 16:10 UTC
Hi, 
I'm trying to run mysql container. But immediately after `docker-compose run -d mysql` the mysql container is `Exited (1)`. 
Logs:
`mysqld: Can't create/write to file '/var/lib/mysql/is_writable' (Errcode: 13 - Permission denied)
2016-08-16T15:44:15.006594Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2016-08-16T15:44:15.011561Z 0 [ERROR] --initialize specified but the data directory exists and is not writable. Aborting.
2016-08-16T15:44:15.011774Z 0 [ERROR] Aborting`

![image](https://cloud.githubusercontent.com/assets/20996605/17706490/ebe1bef2-63e4-11e6-8a6e-121681883e76.png)

I'm trying with:

- Docker version 1.12.0, build 8eab29e

- docker-machine version 0.8.0, build b85aac1

- docker-compose version 1.8.0, build f3628c7

- docker-machine --driver virtualbox

- OS X El Capitan 10.11.6

**Comment by Mahmoudz** [comment] 2016-08-16 22:42
You might need to delete the orphaned volumes in your Docker. I've added a solution for that on Stackoverflow, check out **my answer** [here](http://stackoverflow.com/questions/30604846/docker-error-no-space-left-on-device).

**Comment by wlcx** [comment] 2016-08-25 15:14
This seems to be a permissions issue rather than a space issue: 
`mysqld: Can't create/write to file '/var/lib/mysql/is_writable' (Errcode: 13 - Permission denied)`
I am also getting this issue on OSX using the same versions above.
On Linux the `data/mysql` directory is `chown`'d to 999 (presumably by something in https://github.com/docker-library/mysql/blob/master/5.7/docker-entrypoint.sh) which is the UID mysql runs as in its container, but some experimentation showed that in boot2docker running virtualised in OSX you cannot change folder permissions:
```
docker@default:/Users/wlcx/arbitrary-laravel-project/laradock/data/mysql$ ls -al
total 0
drwxr-xr-x    1 docker   staff           68 Aug 25 15:01 ./
drwxr-xr-x    1 docker   staff          306 Aug 22 15:21 ../

docker@default:/Users/wlcx/arbitrary-laravel-project/laradock/data/mysql$ chown 999:staff

docker@default:/Users/wlcx/arbitrary-laravel-project/laradock/data/mysql$ ls -al
total 0
drwxr-xr-x    1 docker   staff           68 Aug 25 15:01 ./
drwxr-xr-x    1 docker   staff          306 Aug 22 15:21 ../
```

The permissions change fails silently, presumably by design, which is probably the cause of this. As far as I can tell read/write host volumes seem to be a bit of a pain!

**Comment by douglascorrea** [comment] 2016-09-04 21:23
I'm OSX also, giving full permission in `laradock/data/mysql` solved my problem. It is far from ideal, but at least for development enviroment it should work.

```
cd laradock/data
sudo chmod -R 777 mysql
```

**Comment by douglascorrea** [comment] 2016-09-04 22:11
Changing permissions also didn't worked. Then I removed homebrew docker version, and installeed Docker For Mac Beta from here: https://docs.docker.com/docker-for-mac/#download-docker-for-mac

Also installed Kitematic.

And now everything is working fine.

**Comment by Mahmoudz** [comment] 2016-10-10 06:12
There's a big chance this issue has been solved, thus I'll close it now, if it's still there feel free to open it again.

**Closed by Mahmoudz** 2016-10-10 06:12 UTC
Labels: Help Wanted

**Comment by enamul1** [comment] 2017-09-01 12:14
@Mahmoudz 
I am still getting this error.

**Comment by viewplatgh** [comment] 2017-09-15 06:05
I got hit by this issue too when I am using docker on Ubuntu. Removing the `use: "1000:50"` in docker-compose.yml seems help.

**Comment by Gnifle** [comment] 2017-09-15 17:42
@viewplatgh 's solution worked for me. Been toying around with Laradock on both Windows and Ubuntu, and couldn't understand why this was happening.

Removing said line instantly solved the issue, and I can now keep the mysql container running.

**Comment by alexandre78** [comment] 2018-01-24 12:41
Hi everyone, I'm trying to remove user: "1000:50" in docker-compose.yml but I can't find it in file.

**Comment by Gnifle** [comment] 2018-01-24 12:52
@alexandre78 Said line "1000:50" which **viewplatgh** mentioned, was removed in release 5.6.0. This was released on Sep 18, 2017, which was 3 days after I solved said problem.

At the time of my comment, I was using version 5.5.5, where the "1000:50" line was still part of [the previous docker-compose.yml file](https://github.com/laradock/laradock/blob/v5.5.5/docker-compose.yml).

What I'm getting at, is that his old solution unfortunately might not be relevant for you today. Of course depends on what version of Laradock you're currently on.

**Comment by frodomogoni** [comment] 2019-10-14 10:34
> I got hit by this issue too when I am using docker on Ubuntu. Removing the `user: "1000:50"` in docker-compose.yml seems solving it. That `user:...` line seems only useful for OSX/Windows users.

it doesn't solve the problem
in case of using `user: "1000:50"` I've got next trouble
`Initializing database
...
2019-10-14T10:15:35.163850Z 0 [ERROR] InnoDB: Operating system error number 95 in a file operation.
2019-10-14T10:15:35.164056Z 0 [ERROR] InnoDB: Error number 95 means 'Operation not supported'
2019-10-14T10:15:35.164116Z 0 [ERROR] InnoDB: File ./ib_logfile101: 'Linux aio' returned OS error 195. Cannot continue operation
2019-10-14T10:15:35.164151Z 0 [ERROR] InnoDB: Cannot continue operation.`
container is running but mysql can't start

`macOS : 10.14.3`
`$ uname
Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64
`

**Comment by mbulava** [comment] 2020-11-22 07:22
@frodomogoni did you ever figure out your issue?  I'm having the space problem on a ubuntu host...
