### ISSUE TITLE
help

### ISSUE THREAD

**Issue by zhangrxiang** [laradock/laradock#696] opened 2017-03-18 17:07 UTC
hi all!,I'm new developer,I have a problem when I use the cmd 'docker-compose up -d nginx mysql'
ERROR: for applications  Cannot create container for service applications: create .: volume name is too short, names should be at least two alphanumeric characters
I did not found the volume of applications
is it  ' applications:
        image: tianon/true
        volumes:
          - ${APPLICATION}:/var/www '
?

![image](https://cloud.githubusercontent.com/assets/11625343/24074265/37b77d36-0c40-11e7-9703-0a284276aef8.png)

for best wishes!

**Comment by hnquang112** [comment] 2017-03-18 17:18
just upgraded laradock and facing the same problem

**Comment by hnquang112** [comment] 2017-03-18 17:33
I've just found out the solution, @zhangrxiang. I think it's a lack of documentation of `env-example` file. So you'll need to add an environment variable `APPLICATION` into your .env file
To me, I'm using multiple projects setting, so I added `APPLICATION=..`. And for you, I guess it's probably `APPLICATION=/var/www`

**Comment by Chtheile** [comment] 2017-03-18 21:41
add "APPLICATION=../" to your .env/.env-example file

**Comment by zhangrxiang** [comment] 2017-03-19 05:54
thank you,It's my problem. I got the wrong path.

**Comment by georgemr** [comment] 2017-03-19 22:36
I am in Windows 10.  I have faced the same problem as @zhangrxiang. I have added "APPLICATION=.." to my .env file. But I have 4 projects in folder .. but none of the project folders are mapped in the workspace container. Folder /var/www in the workspace container has only folder laradock with 2 folders inside (logs and nginx). Please advice.

**Comment by Mvzundert** [comment] 2017-03-20 09:18
This is definitely an issue with the path not being found correctly, in your case the 4 projects need to be up one directory from where laradock is (or you need to set the application path correctly).

aka:

Laradock
Project 1
Project 2
Project 3
Project 4

**Comment by georgemr** [comment] 2017-03-20 09:39
@Mvzundert the directory structure is as you indicate:
![image](https://cloud.githubusercontent.com/assets/9483995/24094205/3fe15042-0d60-11e7-8b2b-aa1cc56ef2c4.png)

But when running the containers and conecting to workspace no folders are mapped:
![image](https://cloud.githubusercontent.com/assets/9483995/24094541/d5e4d41e-0d61-11e7-9216-6153041ba845.png)


The first line in `.env` file in laradock contains:
`APPLICATION=..`

and `docker-compose.yml` contains:
`    applications:`
`        image: tianon/true`
`        volumes:`
`          - ${APPLICATION}:/var/www`

**Comment by Mvzundert** [comment] 2017-03-20 10:27
@georgemr your syntax is wrong:

`APPLICATION=../`

Would map to the correct location.

**Comment by georgemr** [comment] 2017-03-20 11:37
@Mvzundert its seems to be a bug in windows. I have corrected `env` file per your suggestion but its not working. More over I have changed `docker-compose.yml` to:
`- ${APPLICATION}:/var/www/dev`.

After recreating the containers, folder `dev` is created in `/var/www` but only folder `laradock` exists in `/var/www/dev`:
![image](https://cloud.githubusercontent.com/assets/9483995/24098236/3196c96a-0d72-11e7-8959-3a830c674c84.png)

**Comment by georgemr** [comment] 2017-03-20 11:55
@Mvzundert the problem remains if I target each folder separately. I have inserted in my `docker-compose.yml` the following lines:
```
volumes:
        #  - ${APPLICATION}:/var/www/dev
          - ../finman:/var/www/finman
          - ../osalp:/var/www/osalp
          - ../pcrm:/var/www/pcrm
          - ../pcms:/var/www/pcms    
```

The folders are mapped by no files resides in them even if in the windows host all these folders contain laravel projects:
![image](https://cloud.githubusercontent.com/assets/9483995/24098601/0133cf28-0d74-11e7-81fc-6155ba091b68.png)

**Comment by Mvzundert** [comment] 2017-03-20 12:34
@georgemr sadly I don't have a windows machine to test this out... (on Mac / Linux myself) but what you're telling me indicates that what's happening is:

Laradock should map everything in the folder above it to var/www if you look at how it was solved in the laradock version before the .env file was introduced:

` - ../sample/:/var/www/sample`

It's the same as what you are using now. So if you're using the $(APPLICATION) way of setting things up then ../ isn't getting resolved properly (because you shouldn't only be seeing laradock itself there but everything else as well) so the second solution you where trying should have worked.  

@Mahmoudz maybe somebody with a windows environment can look into this more.

**Comment by a-h-abid** [comment] 2017-03-20 18:52
@georgemr do you have this in your .env file? Might work...

    COMPOSE_CONVERT_WINDOWS_PATHS=1

https://github.com/laradock/laradock/issues/508#issuecomment-269329543

**Comment by georgemr** [comment] 2017-03-20 20:39
@a-h-abid `COMPOSE_CONVERT_WINDOWS_PATHS=1` did the trick. Combined with `APPLICATION=../` everything works fine. Thank you both @Mvzundert and @a-h-abid.

**Comment by Mvzundert** [comment] 2017-03-21 09:00
@a-h-abid  I totally missed that one... good one, I hate not being able to test on windows..

**Comment by Olivia101** [comment] 2017-03-21 09:23
I was about to setup Laradock on my Windows 10 and I'm so glad I saw this issue comment. Perhaps this should be added to the documentation for the all the Windows users out there.

**Comment by Mvzundert** [comment] 2017-03-21 10:19
@Olivia101 I'll create a pull request to add this line to the env-example, as it should just be there to fix this issue, it has no impact on the other OS to have it there.

I just wasnt aware that this got removed and needed to be there.

**Comment by Mvzundert** [comment] 2017-03-21 10:20
@Olivia101 I'll create a pull request to add this line to the env-example, as it should just be there to fix this issue, it has no impact on the other OS to have it there.

I just wasnt aware that this got removed and needed to be there.

**Comment by Mahmoudz** [comment] 2017-03-21 22:01
@zhangrxiang your main problem was caused by the missed `APPLICATION` variable from in `.env` file. If you upgrade your Laradock repo, your problem should be fixed.

@chtheile @georgemr @mvzundert @a-h-abid @Olivia101 the multiple projects setup now works differently after involving the `.env` file. We used to point to each project's folder from the `docker-compose.yml` in the past.

After adding the `.env` I was somehow forced to pointing to a single directory. But that is not a problem for multiple projects setup, since if we change our PHP Server settings, we can tell the server to load the project that we want, and we can also control the domain to access each project. 

In case of NGINX you will need to create `sites` _(samples shipped within Laradock at `laradock-pp/nginx/sites/*`)_  where you simply point to your project's public folder, and also set a default domain for your project.

Please check the updated [documentation](http://laradock.io/getting-started/#installation).

Enjoy :)

**Closed by Mahmoudz** 2017-03-21 22:01 UTC

**Comment by KerrickChan** [comment] 2017-07-27 17:25
COMPOSE_CONVERT_WINDOWS_PATHS not works for windows 10 latest version /.\
