### ISSUE TITLE
Laravel Views not updating on refresh

### ISSUE THREAD

**Issue by edmundluong** [LaraDock/laradock#355] opened 2016-10-10 18:46 UTC
Hi,

I am using Laradock v4.7.2 and have been finding that my Laravel Views have not been updating when I modify them and refresh the browser.

For example, consider the following blade view:

```
<html>
    <head></head>
    <body>
 
    </body>
</html>
```

After modifying the view, it looks like such:

```
<html>
    <head></head>
    <body>
        <div>Hello, world</div>
    </body>
</html>
```

However, after refreshing my browser I do not see these changes reflected. I have tried running `php artisan cache:clear` and `php artisan views:clear` but had no luck in resolving this issue.

After doing [some investigation](http://stackoverflow.com/questions/20579182/laravel-and-view-caching-in-development-cant-see-changes-right-away), it appears it is a caching issue related to PHP and Opcache, and not Laravel itself.

I was able to add the following modify/add the following lines to my `opcache.ini` in laradock/php-fpm to get this working again:

```
extension=opcache.so
opcache.enable="1"
opcache.memory_consumption="256"
opcache.use_cwd="0"
opcache.fast_shutdown="1"
opcache.max_file_size="0"
opcache.validate_timestamps="1" // Modify 0 to 1
opcache.revalidate_freq="0" // Add this line
```

I am not sure if this is an isolated issue or not, so I thought I would post this and see if anybody was running into the same issue. I do not mind making a PR if this is indeed a widespread issue.

**Comment by Mahmoudz** [comment] 2016-10-10 23:16
@edmundluong actually someone had the same problem here #337 and he was able to solve it in another way, however, if your solution works just fine feel free to submit a PR.. I personally didn't used opcache yet.. so let's see what @philtrep and @lukasoppermann think.

**Comment by philtrep** [comment] 2016-10-11 18:30
@edmundluong @Mahmoudz

I don't know much about Opcache but from what I gather, the fix would make the application less performant since it would be looking for file modifications on every request.

It seems to me that we almost only need caching for non-dev environments so this shouldn't be a problem for most people but we should add a section in the docs, probably in the _Production_ section, explaining this since it's not the default behavior (assuming the config we currently have is the default one).

**Comment by lukasoppermann** [comment] 2016-10-11 20:08
Yes, this seems to not be good, as `opcache.revalidate_freq` effectifly means it is revalidated in every request.

`opcache.validate_timestamps` though would be good (and is needed if `opcache.revalidate_freq` is used).

`opcache.revalidate_freq` sets the time in seconds at which the cached files are revalidated, however revalidation is NOT the same as compiling, it is not as slow as no opcache at all.

**Comment by deleonn** [comment] 2016-10-16 08:09
Already tried with the opache.ini fix with no luck, I can barely code properly as views are not refreshing. I been jumping from stable to beta version of docker for mac but the results are the same. I literally have to reset my machine in order to see some changes in my app.

**Comment by philtrep** [comment] 2016-10-18 12:57
@deleonn Glad you got everything working! I'll close this for now, if we get more people with the same issue we'll take a closer look at the caching mechanism.

**Closed by philtrep** 2016-10-18 12:57 UTC
Labels: Help Wanted, Possible Bug

**Comment by ChangePlaces** [comment] 2017-12-05 16:40
Take note of the answer regarding PHPStorm

https://stackoverflow.com/questions/37503627/blade-view-not-reflecting-changes

**Comment by otim22** [comment] 2018-03-03 14:05
Hey guys, I know this issues has been closed but am running into it using Homestead and Laravel 5.6.
Any help, I have tried:  php artisan cache:clear and  php artisan views:clear not helpful at all.

**Comment by donprecious** [comment] 2018-12-13 10:53
am having same issue, old version of views shows up, my route, controlller code does not reflect, i have cleared cache but the problem still persist, am really hooked now, i recently added git to the project dont know if that was the cause of the problem

**Comment by usudath** [comment] 2019-01-17 10:06
Clear Cache and Views and regenerating the Key solved my problem.

**Comment by stea4lth** [comment] 2023-09-28 09:09
`php artisan key:generate` solved it for me.
