### ISSUE TITLE
"Unable to load dynamic library..." for all enabled PDO extensions

### ISSUE THREAD

**Issue by midnightelf** [laradock/laradock#2844] opened 2021-02-21 20:14 UTC
### Description:
I have a project for laravel. And I launch this project through the laradock. I run `workspace`, `php-fpm` and `mysql` containers. In the `workspace` in the `php.ini` file, I uncommented `;extensions=pdo_mysql`, then I start the database migration and get an error
```
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_mysql' (tried: /usr/lib/php/20180731/pdo_mysql (/usr/lib/php/20180731/pdo_mysql: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/pdo_mysql.so (/usr/lib/php/20180731/pdo_mysql.so: undefined symbol: mysqlnd_allocator)) in Unknown on line 0

   Illuminate\Database\QueryException

  SQLSTATE[HY000] [2002] No such file or directory (SQL: select * from information_schema.tables where table_schema = toph and table_name = migrations and table_type = 'BASE TABLE')

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:678
    674▕         // If an exception occurs when attempting to run a query, we'll format the error
    675▕         // message to include the bindings with SQL, which will make this exception a
    676▕         // lot more helpful to the developer instead of just the database's errors.
    677▕         catch (Exception $e) {
  ➜ 678▕             throw new QueryException(
    679▕                 $query, $this->prepareBindings($bindings), $e
    680▕             );
    681▕         }
    682▕

      +33 vendor frames
  34  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

   Whoops\Exception\ErrorException

  PHP Startup: Unable to load dynamic library 'pdo_mysql' (tried: /usr/lib/php/20180731/pdo_mysql (/usr/lib/php/20180731/pdo_mysql: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/pdo_mysql.so (/usr/lib/php/20180731/pdo_mysql.so: undefined symbol: mysqlnd_allocator))

  at Unknown:0
      1▕

      +1 vendor frames
  2   [internal]:0
      Whoops\Run::handleShutdown()
```
and the command `php -m` output the following

```
root@e581f40484a7:/var/www# php -m
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_mysql' (tried: /usr/lib/php/20180731/pdo_mysql (/usr/lib/php/20180731/pdo_mysql: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/pdo_mysql.so (/usr/lib/php/20180731/pdo_mysql.so: undefined symbol: mysqlnd_allocator)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_pgsql' (tried: /usr/lib/php/20180731/pdo_pgsql (/usr/lib/php/20180731/pdo_pgsql: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/pdo_pgsql.so (/usr/lib/php/20180731/pdo_pgsql.so: undefined symbol: pdo_parse_params)) in Unknown on line 0
PHP Warning:  Module 'curl' already loaded in Unknown on line 0
[PHP Modules]
ast
bcmath
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
igbinary
intl
json
libxml
mbstring
memcached
msgpack
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

```

### Expected Behavior:

successfully migrate )

**Output of `docker version`**

```
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:17:34 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```
**Output of `php -i | grep -i ^pdo`**

```
root@97919140e223:/var/www# php -i | grep -i ^pdo
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_mysql' (tried: /usr/lib/php/20180731/pdo_mysql (/usr/lib/php/20180731/pdo_mysql: cannot open shared object file: No such file or directory), /usr/lib/php/20180731/pdo_mysql.so (/usr/lib/php/20180731/pdo_mysql.so: undefined symbol: mysqlnd_allocator)) in Unknown on line 0
PDO
PDO support => enabled
PDO drivers => mysql, pgsql, sqlite
pdo_mysql
PDO Driver for MySQL => enabled
pdo_mysql.default_socket => /var/run/mysqld/mysqld.sock => /var/run/mysqld/mysqld.sock
pdo_pgsql
PDO Driver for PostgreSQL => enabled
pdo_sqlite
PDO Driver for SQLite 3.x => enabled
```

**Output of `docker-compose version`**

```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**System info: Mac, Windows or Linux. Include which disto/version**

```
OS: Ubuntu 20.04.2 LTS on Windows 10 x86_64
Kernel: 5.4.72-microsoft-standard-WSL2
Uptime: 3 hours, 37 mins
Packages: 645 (dpkg)
Shell: bash 5.0.17
Terminal: /dev/pts/1
CPU: Intel i5-9300H (8) @ 2.399GHz
Memory: 1461MiB / 6226MiB
```

### Steps to reproduce the issue:

1. clone laradock repository
2. up php-fpm workspace containers
3. uncomment `;extensions=pdo_mysql` or any other pdo extension
4. run `artisan migrate`

**Comment by MannikJ** [comment] 2021-02-25 16:50
Same problem here. Is there any quick workaround?

**Comment by nosferatu-id** [comment] 2021-02-25 17:50
> Same problem here. Is there any quick workaround?

there is no solution like this, but you can temporarily transfer your work environment to the work environment. I have windows. I have not found another solution yet

**Comment by glebovdev** [comment] 2021-03-06 14:56
I'm not sure do I need to create a separate issue or it's all about the same.
```
PHP Warning:  PHP Startup: Unable to load dynamic library 'memcached.so' (tried: /usr/lib/php/20190902/memcached.so (/usr/lib/php/20190902/memcached.so: undefined symbol: igbinary_serialize), /usr/lib/php/20190902/memcached.so.so (/usr/lib/php/20190902/memcached.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```
But in my case, the issue is about `php-memcached` module.  
PHP version in my case - 7.4. 
I receive this warning already when the container is building, and of course, after it was built.
Here's my small investigation.

I log in as a root inside workspace container:
`docker-compose exec --user=root workspace bash`

Checking for warning:
`php -v`

and I get:
`PHP Warning:  PHP Startup: Unable to load dynamic library 'memcached.so' .... undefined symbol: igbinary_serialize....` (full version is above)

Checking memcached module version with `dpkg -l  | grep memcached` and I see `3.1.4+2.2.0-1+ubuntu18.04.1+deb.sury.org+20191129`

Then I do (still as a root):
```
apt update
apt install php7.4-memcached
```
A new version of the module is installing and now the version is `3.1.5+2.2.0-9+ubuntu18.04.1+deb.sury.org+1`. And I don't see any other warnings after that.

BUT I suppose this shouldn't work like this and I hope there is a way to avoid manual module updates and still have no php-related warnings inside the workspace container.

Maybe it's all about the base `workspace` image.

**Comment by rcargnelutti** [comment] 2021-03-25 03:01
Hello!

I use **laradock**.

Running "**php artisan migrate**" in the application directory on the local machine this problem occurs.

I solved it by running "**php artisan migrate**" inside the **docker container** with **laravel** application:
**sudo docker-compose exec workspace bash**

Access the application directory and perform the migrate
**php artisan migrate**

Hope this helps!

Hugs...

**Comment by bestlong** [comment] 2021-03-27 15:39
@nosferatu-id 
laradock use `.env` control php extension install
step:
edit `.env` (copy from env-example) set u need extension ****=true
run command `docker-compose build workspace`

**Comment by ngmy** [comment] 2021-04-03 10:51
> I'm not sure do I need to create a separate issue or it's all about the same.
> 
> ```
> PHP Warning:  PHP Startup: Unable to load dynamic library 'memcached.so' (tried: /usr/lib/php/20190902/memcached.so (/usr/lib/php/20190902/memcached.so: undefined symbol: igbinary_serialize), /usr/lib/php/20190902/memcached.so.so (/usr/lib/php/20190902/memcached.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
> ```

This seems to be fixed in the current master.

**Closed** 2021-04-07 16:03 UTC
Labels: Type: Bug

**Comment by JexPY** [comment] 2021-06-25 18:31
> laradock use `.env` control php extension install
> step:
> edit `.env` (copy from env-example) set u need extension ****=true
> run command `docker-compose build --no-cache --pull workspace`

For me only:

`apt -y remove php-memcached`

Solved the warning.
