### ISSUE TITLE
I'm using laradock for Codeigniter 3

### ISSUE THREAD

**Issue by manshoor** [LaraDock/laradock#387] opened 2016-10-24 14:33 UTC
I'm getting this issue in my project.

PHP Startup: Invalid library (appears to be a Zend Extension, try loading using zend_extension=opcache.so from php.ini)

**Comment by philtrep** [comment] 2016-10-24 14:50
I believe this is a duplicate of #325

**Closed by philtrep** 2016-10-24 14:50 UTC
Labels: Duplicate

**Comment by Mahmoudz** [comment] 2016-10-24 18:16
@manshoor could you share with us the steps of how to setup codeigniter on laradock? I'd like to mention that in the documentation. If you prefer you can send a PR or just comment it here and I'll move it to a new section in the docs. Thanks.

**Comment by manshoor** [comment] 2016-10-25 21:26
@Mahmoudz 
yes sure, it's actually the same as Laravel but here is the only change for mysqli extension in php-fpm/Dockerfile-56

# PHP extensions

RUN docker-php-ext-install mysqli

RUN docker-php-ext-install tokenizer

**Comment by Mahmoudz** [comment] 2016-10-31 16:26
@manshoor could you try the last laradock release 4.8.0 and confirm that Codeigniter is running perfectly, you may need to check this section for some help [https://github.com/LaraDock/laradock#Install-Codeigniter](https://github.com/LaraDock/laradock#Install-Codeigniter) Thanks.

**Comment by manshoor** [comment] 2016-11-03 10:00
@Mahmoudz Yep it worked like a charm (y)
I'm setting up a Symfony application on Laradock, I'll share the PR with you :)

**Comment by Mahmoudz** [comment] 2016-11-03 13:42
@manshoor amazinggg thanks

**Comment by mjawaids** [comment] 2017-03-09 15:40
I've tried to use CodeIgniter but page always shows Nginx 404 page. I've tried the suggestions above and from #325 but still not working.

**Comment by manshoor** [comment] 2017-03-09 15:55
enable `CODEIGNITER=true` in docker compose and in nginx config map the public folder correctly like this 

```
server_name projectName.local;

root /var/www/projectName/public_html;

```

**Comment by mjawaids** [comment] 2017-03-09 16:18
I already enabled the codeigniter=true but didn't configure nginx as wanted
to run default with localhost.

**Comment by manshoor** [comment] 2017-03-09 16:30
so, now is it working fine?

**Comment by mjawaids** [comment] 2017-03-09 17:21
Nope.

**Comment by magicuniverse-azeem** [comment] 2017-10-03 20:40
@manshoor were you able to set symfony project. Is there a PR for it?
