### ISSUE TITLE
How to install ext-rar

### ISSUE THREAD

**Issue by earosb** [laradock/laradock#618] opened 2017-02-20 14:13 UTC
Hello, I need to install [UnifiedArchive](https://github.com/wapmorgan/UnifiedArchive) so far I created a new condition in the dockerfile file and added the key in the file docker-compose.yml, then run `docker build php-fpm`

```
ARG INSTALL_RAR_ARCHIVE=false
RUN if [ ${INSTALL_RAR_ARCHIVE} = true ]; then \
    # Install the rar extension
    pecl install rar && \
    docker-php-ext-enable rar \
;fi
```
Error message
```
/tmp/pear/temp/rar/rar.c: At top level:
cc1: warning: unrecognized command line option "-Wno-logical-op-parentheses"
Makefile:194: recipe for target 'rar.lo' failed
make: *** [rar.lo] Error 1
ERROR: `make' failed
error: /usr/local/lib/php/extensions/no-debug-non-zts-20151012/rar does not exist

usage: /usr/local/bin/docker-php-ext-enable [options] module-name [module-name ...]
   ie: /usr/local/bin/docker-php-ext-enable gd mysqli
       /usr/local/bin/docker-php-ext-enable pdo pdo_mysql
       /usr/local/bin/docker-php-ext-enable --ini-name 0-apc.ini apcu apc

Possible values for module-name:
gd.so mcrypt.so opcache.so pdo_mysql.so pdo_pgsql.so zip.so
ERROR: Service 'php-fpm' failed to build: The command '/bin/sh -c if [ ${INSTALL_RAR_ARCHIVE} = true ]; then     pecl install rar &&     docker-php-ext-enable rar ;fi' returned a non-zero code: 1`
```

**Comment by francislavoie** [comment] 2017-02-20 22:57
That's not a laradock issue, a quick google gave me this https://bugs.php.net/bug.php?id=63016, so it looks like it's a bug in the rar package. You might need to try and make a fix yourself and build it from the `.tgz`. Doesn't look like it's maintained anymore, last release being in 2013.

**Comment by francislavoie** [comment] 2017-02-20 23:04
Actually it looks like the problem is that the `gcc` version is too old and doesn't have that `-Wno-logical-op-parentheses` option included.

**Comment by philtrep** [comment] 2017-02-24 00:52
Closing this based on @francislavoie 's comment that this issue is not Laradock related

**Closed by philtrep** 2017-02-24 00:52 UTC

**Comment by ErnestStaug** [comment] 2020-05-11 19:56
If anyone stumbles this thread why having `rar` extension issues...
On php 7.4 given pecl extensions couldn't compile, this repo saved me https://github.com/esminis/php_pecl_rar
