### ISSUE TITLE
redis doesn't work

### ISSUE THREAD

**Issue by efsjouw** [laradock/laradock#3361] opened 2023-03-07 15:42 UTC
### Description:
redis doesnt appear to work, it appears unreachable or refuses connection?

using Windows / WSL / Docker Desktop setup with Laravel 9.

### Expected Behavior:
connect to redis at localhost:6379

### Context information:

Not much to show I just use

`docker-compose up redis`

and then it is not available at http://localhost:6379/

In Laravel the error "Connection refused" is shown

**Comment by rubensrocha** [comment] 2023-05-21 14:01
.env file (Laradock), line 422:

REDIS_PASSWORD=secret_redis

.env (Laravel)
REDIS_HOST=redis
REDIS_PASSWORD=secret_redis
REDIS_PORT=6379

**Comment by makowskid** [comment] 2023-07-31 21:10
not a bug, just a small annoyance after `.env` requirements change in the meantime 

whoever stumbles upon this issue - please remember to check `REDIS_PASSWORD=secret_redis` line in `.env` file

closing this issue

**Closed by makowskid** 2023-07-31 21:10 UTC
Labels: Type: Bug

**Comment by myDisconnect** [comment] 2023-09-15 08:20
This is definitely a bug, you cannot use redis without password due to docker-compose.yml

> command: --requirepass ${REDIS_PASSWORD}

**Comment by makowskid** [comment] 2023-09-18 14:27
Why would you want to use Redis without a password?
There's a solution for it now, and it's setting the default Laradock password inside `.env`.
`REDIS_PASSWORD=secret_redis`

Doesn't it solve your issue?
