### ISSUE TITLE
php-fpm fails to start port 22 already allocated

### ISSUE THREAD

**Issue by unfortunatetoast** [LaraDock/laradock#281] opened 2016-09-02 21:13 UTC
When I run

`docker-compose up -d nginx mysql redis`

I get the following output:

Starting laradock_volumes_source_1
Starting laradock_volumes_data_1
laradock_workspace_1 is up-to-date
Starting laradock_php-fpm_1
laradock_redis_1 is up-to-date
laradock_mysql_1 is up-to-date

ERROR: for php-fpm  Cannot start service php-fpm: driver failed programming external connectivity on endpoint laradock_php-fpm_1 (e179ff36c0cd5a605a8fac3ec0401cc494c4b9477426859a3d81750b24886cba): Bind for 0.0.0.0:22 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.

I closed out all other programs and I checked and the only other program using port 22 is laradock_workspace. I checked the docker-compose.yml and it appears that both the workspace and php-fpm require ports 22 which cause docker to fail?

**Comment by unfortunatetoast** [comment] 2016-09-02 21:34
Also,
Docker version 1.12.0, build 8eab29e
docker-compose version 1.8.0, build f3628c7

I also tried restarting docker service

**Comment by LarryEitel** [comment] 2016-09-02 21:37
Please remove the reference to port 22 in docker-compose / php-fpm container and rebuild it. While you may want to connect to workspace on port 22, you shouldn't need to with php-fpm.

**Comment by unfortunatetoast** [comment] 2016-09-02 22:14
@LarryEitel I removed the reference to port 22 i.e. - "22:22" under php-fpm container in docker-compose.yml now I get this error:
ERROR: for nginx  Cannot start service nginx: driver failed programming external connectivity on endpoint laradock_nginx_1 (2ddffb0275b7a0998c2b7af2bd56a5861cf04d2850505336c0e925459ba9a7ce): Error starting userland proxy: Bind for 0.0.0.0:80: unexpected error (Failure EADDRINUSE)

**Comment by LarryEitel** [comment] 2016-09-02 22:16
If you use Skype, check Tools/Options/Advanced/Connections and make sure ports 80/443 are not checked. Also, make sure you do not have some other web-server running on your host.

**Comment by unfortunatetoast** [comment] 2016-09-02 22:29
@LarryEitel in terminal I ran 
'lsof -i TCP:80'
And it showed a bunch of stuff from google (chrome I guess). So I shut down chrome, ran that command again and saw nothing using port 80. Restarted docker, ran 'docker-compose up -d nginx mysql redis' and got the same bind error for nginx on port 80

**Comment by LarryEitel** [comment] 2016-09-02 22:31
Interesting... Try starting only nginx.

**Comment by Shmp** [comment] 2016-09-03 10:52
Have the same problem, the workspace will not start either because of port 22.

**Comment by LarryEitel** [comment] 2016-09-03 11:51
Try changing in docker-compose / workspace container the port reference from "22:22" to something like "2200:22".

**Comment by SilverPaladin** [comment] 2016-09-03 15:08
I had the same issue. I changed my docker-compose.yml line in php-fpm section from `- "22:22`" to - `"9000:9000`"

**Comment by douglascorrea** [comment] 2016-09-03 18:23
Maybe we don't need the port:22 at all. Since we use docker-compose exec workspace bash to start using in the workspace we don't need to ssh to it.

At least it works in OSX with docker-machine, but I think it is the same for docker in linux boxes.

**Comment by LarryEitel** [comment] 2016-09-03 19:18
@douglascorrea Actually it IS needed for those who need to do 'remote' debugging such as when using an IDE like PHPStorm. The IDE actually connects to PHP remotely via, in this case, port 22. IF that port is needed by another app/service, just map it to an unused port, for example, "2200:22".

@SilverPaladin php-fpm exposes port 9000 by default. No need to explicitly, do so in docker-compose.

**Comment by sakanaproductions** [comment] 2016-09-03 19:46
I tried changing the port from 22 to 2200 now I'm getting the same thing: ERROR: for php-fpm  Cannot start service php-fpm: driver failed programming external connectivity on endpoint laradock_php-fpm_1 (99ddd955e0d334424742a6a6a044f687ff8e4304cde85f00ef9bf312512a9e6c): Bind for 0.0.0.0:2200 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.

**Comment by LarryEitel** [comment] 2016-09-03 19:52
Curious, did completely remove all LaraDock containers and laradock_* images and then restart? I don't see how/why php-fpm would have a reason complain about port 2200! :(

**Comment by sakanaproductions** [comment] 2016-09-03 19:54
@LarryEitel I think it was because both workspace and php-fpm are trying to use 22 at the same time, so doing port forwarding on different ports seemed to resolve

**Comment by LarryEitel** [comment] 2016-09-03 20:04
It should be a non-issue at this point because a PR was merged that removed port 22 from php-fpm. :)

**Comment by sakanaproductions** [comment] 2016-09-03 21:42
@LarryEitel so it'd be okay for me to remove port 22 from php-fpm?

**Comment by LarryEitel** [comment] 2016-09-03 22:15
@sakanaproductions If you removed port 22 from php-fpm, then your port 22 conflict would be with workspace right? But if you map workspace port 22 to another port, I don't understand why/how you would still have a problem. For what ever it is worth, please make sure you completely remove and rebuild all images and containers. I sympathize with your frustration. When things work, it is GREAT!! :)

**Comment by gkweb** [comment] 2016-09-09 01:55
I can confirm I'm having a similiar problem. Port 22 already assigned connectivity issue. No other programs on my computer are using 22. 

`ERROR: for workspace  Cannot start service workspace: driver failed programming external connectivity on endpoint laradock_workspace_1 (046b4c08bb65bad79e8d8ce0f31191a249893f9b2ac935026da913bae5f46fb8): Error starting userland proxy: listen tcp 0.0.0.0:22: bind: address already in use`

**Comment by gkweb** [comment] 2016-09-09 06:47
I solved this problem by completely uninstalling Docker toolbox and using Docker for Mac. 
No direct solution but it appears to have worked for my local dev environment. 

Remove docker like so:
[manually uninstall docker toolbox](https://therealmarv.com/how-to-fully-uninstall-the-offical-docker-os-x-installation/)
install docker for mac:
https://docs.docker.com/docker-for-mac/

**Comment by edmundluong** [comment] 2016-09-10 19:36
Also running into this issue on Debian 8.5

docker version 1.12.1, build 23cf638
docker-compose version 1.8.0, build f3628c7

**Comment by g0ld3lux** [comment] 2016-09-13 05:36
This will Fix this ISSUE...

1.) Check What Kind of Docker Installation You Used...
a.) Windows/Mac Version
b.) Docker ToolBox

if you are Using the Latest Version of Docker for Windows or For MAC
Use the Master Branch...

Then You Can Do docker-compose up without any trouble 

BUT

if you are Using the Docker ToolBox , which i am, 
after you git clone the repo, do a git checkout LaraDock-ToolBox

If you didnt do that You will face this issue...
so Make Sure you Check OUT to the LaraDock-ToolBox Branch

HOPE IT HELPS

**Closed** 2016-09-14 01:22 UTC

**Comment by devblaze** [comment] 2021-11-21 17:59
> This will Fix this ISSUE...
> 
> 1.) Check What Kind of Docker Installation You Used... a.) Windows/Mac Version b.) Docker ToolBox
> 
> if you are Using the Latest Version of Docker for Windows or For MAC Use the Master Branch...
> 
> Then You Can Do docker-compose up without any trouble
> 
> BUT
> 
> if you are Using the Docker ToolBox , which i am, after you git clone the repo, do a git checkout LaraDock-ToolBox
> 
> If you didnt do that You will face this issue... so Make Sure you Check OUT to the LaraDock-ToolBox Branch
> 
> HOPE IT HELPS

Well, I am using docker's latest version (did not `git checkout LaraDock-ToolBox` since I am not using toolbox) and I am getting that error.
