### ISSUE TITLE
Error: Build failed

### ISSUE THREAD

**Issue by Mahmoudz** [laradock/laradock#889] opened 2017-05-04 08:18 UTC
<img width="978" alt="screen shot 2017-05-04 at 4 17 20 am" src="https://cloud.githubusercontent.com/assets/1983984/25695327/a384bfd8-3080-11e7-98a2-28f2913a2517.png">

**Comment by winfried-van-loon** [comment] 2017-05-04 08:22
I think this is a duplicate of #855?

**Comment by bestlong** [comment] 2017-05-04 09:21
About V8JS ERROR, Fixing by #887

**Comment by winfried-van-loon** [comment] 2017-05-07 15:41
Should be fixed now by #906. However if you're still experiencing the issue, feel free to leave a comment.

**Closed by winfried-van-loon** 2017-05-07 15:41 UTC
Labels: Flag: Duplicate, Type: Bug
