### ISSUE TITLE
Credentials from env not applied to mariadb

### ISSUE THREAD

**Issue by garlian** [laradock/laradock#739] opened 2017-04-04 17:51 UTC
It seems like the mariadb doesnt recognize the .env file which i copied from env-example, everthing is build up fine if I start my nginx and mariadb via docker-compose but if I access the mariadb container and try to access the db via:
`mysql -u root -p default`

It always tell me access denied. I tried to rebuild, I tried different default credentilas, nothing worked. On the other side if I use mysql everthing worked fine out of the box with root/root as combination.

I´m on Windows 10, havent tried on ubuntu yet.

Any ideas?

**Comment by winfried-van-loon** [comment] 2017-04-04 21:50
This may be a duplicate of #736 which wasn't fully fixed.

**Comment by Mahmoudz** [comment] 2017-04-05 00:47
@garlian this should be solved, please update your Laradock and don't forget to rebuild your containers after every update.
@winfried-van-loon Thanks for your help :)

**Closed by Mahmoudz** 2017-04-05 00:47 UTC

**Comment by garlian** [comment] 2017-04-05 09:01
Tried the same procedure again after pulling the latest updates, no success.

I removed container and images completely, rebuild everything from scratch but still no access. Maybe a Windows thing?

My process:
`docker-compose up -d nginx mariadb`
`docker exect -it laradock_mariadb_1 bash` 
`mysql -u root -p default` after prompt entering my credential password, which I set in my .env file

btw: The Dockerfile-71 in workspace has a wrong placed comment (making the build fail) in Line 13.

**Comment by winfried-van-loon** [comment] 2017-04-05 09:23
It didn't work for me as well. However, I've just now completely removed all of my Docker stuff: Images, containers, volumes - everything. Docker for Mac has a handy "Reset to factory defaults" button, which does that process automatically. I've then used the following command to bring up Apache2 with MariaDB:

```
docker-compose up -d --force-recreate --build apache2 mariadb
```

Which worked. (with a bunch of warnings, will put in some more pull requests in the future for those.) After which, I could connect to the database using `root` and `default` on both SQL directly and SQL over SSH (workspace).

**Comment by garlian** [comment] 2017-04-05 10:30
Okay, I tried the same solution, after some little hiccups I can now enter mariadb. But to reset to factory defaults is a little bit overkill, isn't it? I think the volume has been the Problem, since images and containers have been rebuild before. I'm not very experienced with docker, will the .env file only be loaded once during build process or everytime I boot up the container?

I noticed that the env key MARIADB_PASSWORD won't work for default, is this normal behaviour?

So far thx!

**Comment by winfried-van-loon** [comment] 2017-04-05 11:22
Yep, the "Reset to factory defaults" was to test more than just the single test, as well. :) It was, however, a perfect time to test things as it was a "fresh" docker install.

MariaDB comes with two users. One user to admin the server. By default has access to everything and all commands. Username is `root`, within the env-sample you can set the `MARIADB_ROOT_PASSWORD` to the password, defaulting to `root`.

The other user is the "application" user, the one you can configure Laravel to use. Username is set to `MARIADB_USER`, password to `MARIADB_PASSWORD`. Make sure the user has access to the database in question and use the `FLUSH PRIVILEGES;` command after changing rights. Should work then - at least, it does for me.
