### ISSUE TITLE
why not add BC Math in CLI

### ISSUE THREAD

**Issue by royen-go** [laradock/laradock#458] opened 2016-11-30 09:41 UTC
I need write some test code about rabbitMQ but there is no BC Math ext in php-cli
```
1) RabbitTest::testAdd
Error: Call to undefined function PhpAmqpLib\Wire\bcadd()

/var/www/pindan/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Wire/AMQPWriter.php:274
/var/www/pindan/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:412
/var/www/pindan/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Connection/AbstractConnection.php:367
/var/www/pindan/vendor/php-amqplib/php-amqplib/PhpAmqpLib/Channel/AMQPChannel.php:1110
/var/www/pindan/vendor/mookofe/tail/src/Message.php:73
/var/www/pindan/vendor/mookofe/tail/src/Message.php:57
/var/www/pindan/vendor/mookofe/tail/src/Tail.php:27
/var/www/pindan/vendor/illuminate/support/Facades/Facade.php:219
/var/www/pindan/tests/RabbitTest.php:18
```

**Comment by philtrep** [comment] 2016-11-30 12:54
This is a duplicate of #453

**Closed by philtrep** 2016-11-30 12:54 UTC
Labels: Duplicate
