### ISSUE TITLE
404 not found - nginx

### ISSUE THREAD

**Issue by kneipp** [LaraDock/laradock#108] opened 2016-06-20 23:50 UTC
Hi there!
I stucked after change volumes to:
            - /c/Users/path/:/var/www/laravel

What do i have to do to work? How sync host and guess?
On workspace ssh i found only default files and laradock nginx log.
On browser i got 404 not found - nginx.

**Comment by sirago** [comment] 2016-07-01 16:40
I'm getting this too. I bashed into my nginx container and the only thing I see in /var/www/laravel is a laradock folder.

**Comment by ivanji** [comment] 2016-07-02 10:16
Exactly the same here. Stuck as well. I'm using the Docker Beta. I have all my projects on a different drive - so I selected it under my 'Shared Drives' thinking this was the cause, but even if my test project is under C:\Users\.. I dont see any of my files. 

@kneipp are you also using this beta version?

**Comment by Kauhat** [comment] 2016-07-02 13:11
I'm also using the Docker Windows Beta, and I'm getting the same issues on my home PC. It seems not to be a LaraDock problem, as other containers can't see the file system either. Can you folk see any of you user files by running the below command?

```
docker run -v c:/Users:/data alpine ls /data
```

Here's [the biggest thread](https://forums.docker.com/t/volume-mounts-in-windows-does-not-work/10693) on the forums about the problem. You might find something that works there (e.g. turn the firewall off), although nothing has fixed it for me yet.

Very strange since it's always worked fine on my work computer.

**Comment by ivanji** [comment] 2016-07-03 01:44
oh yes, definitely not a Laradock issue. Thanks for that link. I'll investigate further and see if any of that solves it for me - and post back. Thanks for your help.

**Comment by sirago** [comment] 2016-07-03 02:07
I was able to fix this on Windows 10. My issue was with the Docker beta. No containers were able to see my files. The fix for me was to create a new Windows account and share that account with Docker. I'm not sure if it was an issue with my account being a Microsoft account or special characters in my password.

**Comment by ivanji** [comment] 2016-07-05 12:07
Thanks again for providing the link to that thread - after a couple of days of playing around with this I managed to find the cause - Norton Firewall. Don't know if I should be happy that I solved it or sad that I wasted so long in such a silly issue. I'm trying to stay positive, at least I got to understand Docker a bit more. 

This is the link with the solution that worked for me: https://forums.docker.com/t/volume-mounts-in-windows-does-not-work/10693/80

**Comment by kneipp** [comment] 2016-07-06 02:36
Here 

$ docker -v
Docker version 1.11.2, build b9f10c9

docker_application_1 exited with code 0

$ docker-compose.exe ps
        Name                     Command             State                     Ports
------------------------------------------------------------------------------------------------------
docker_application_1   true                          Exit 0
docker_data_1          true                          Exit 0
docker_mysql_1         docker-entrypoint.sh mysqld   Up       0.0.0.0:3306->3306/tcp
docker_nginx_1         nginx                         Up       0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp
docker_php-fpm_1       php-fpm                       Up       9000/tcp
docker_workspace_1     /sbin/my_init                 Up

**Comment by Mahmoudz** [comment] 2016-07-15 17:03
This issue was opened before #86 so I'll close this one to keep the conversation in one place.

**Closed by Mahmoudz** 2016-07-15 17:03 UTC
Labels: Question
