### ISSUE TITLE
Setup Xdebug with PHP55-FPM image

### ISSUE THREAD

**Issue by reypm** [laradock/laradock#334] opened 2016-09-28 13:09 UTC
I need some advice setting up Xdebug in php55-fpm meaning I don't know if I can use the same block from php7--fpm Dockerfile:

```
#####################################
# xDebug:
#####################################

ARG INSTALL_XDEBUG=true
RUN if [ ${INSTALL_XDEBUG} = true ]; then \
    # Install the xdebug extension
    pecl install xdebug && \
    docker-php-ext-enable xdebug \
;fi

# Copy xdebug configration for remote debugging
COPY ./xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini
```

Is it possible? Which would be the best way to achieve this?

**Comment by reypm** [comment] 2016-09-28 18:52
@Mahmoudz the only thing I am not sure at all is about this line: `pecl install xdebug` since I have previously installed xdebug as `apt-get install php55-xdebug`. What would be your suggestion?

**Comment by appleboy** [comment] 2016-09-29 01:05
@reypm I prefer the command `apt-get install php55-xdebug`.

**Comment by reypm** [comment] 2016-09-29 12:26
@appleboy I am lost, what `docker-php-ext-install` will do for me that `apt-get` install will not? At this point I don't know if I should install xdebug using `apt` or `docker-php-ext-install`. 

@Mahmoudz  I have read the [Dockerfile-56](https://github.com/LaraDock/php-fpm/blob/master/Dockerfile-56) and I am notice the following:

```
FROM php:5.6-fpm
MAINTAINER Mahmoud Zalt <mahmoud@zalt.me>

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        curl \
        libmemcached-dev \
        libz-dev \
        libpq-dev \
        libjpeg-dev \
        libpng12-dev \
        libfreetype6-dev \
        libssl-dev \
        libmcrypt-dev

RUN docker-php-ext-install mcrypt
RUN docker-php-ext-install pdo_mysql
RUN docker-php-ext-install pdo_pgsql

RUN docker-php-ext-install gd && \
    docker-php-ext-configure gd \
        --enable-gd-native-ttf \
        --with-jpeg-dir=/usr/lib \
        --with-freetype-dir=/usr/include/freetype2 && \
    docker-php-ext-install gd
```

Why `docker-php-ext-install gd` appears twice? I am confused.

**Comment by appleboy** [comment] 2016-09-29 12:42
@reypm I will fix the duplicate of `docker-php-ext-install gd`.

**Comment by reypm** [comment] 2016-09-29 12:58
@appleboy sadly there is another issue, I have opened another issue, take a look :-( and I have one more I will test once again and if I can not get this working I'll be opening another one :)

**Comment by Mahmoudz** [comment] 2016-10-10 06:37
@reypm if this issue is solved, please close this Issue and let's carry the conversation on your new opened Issue. Thanks

**Comment by reypm** [comment] 2016-10-10 11:37
@Mahmoudz isn't fixed, check the file [Dockerfile-56][1]

 [1]: https://github.com/LaraDock/php-fpm/blob/master/Dockerfile-56

**Comment by Mahmoudz** [comment] 2016-10-10 12:51
@reypm yes I think so. I'll close this now. Thanks

**Comment by reypm** [comment] 2016-10-10 16:20
@Mahmoudz I am seeing exactly the same content:

```
# Install the PHP gd library
RUN docker-php-ext-install gd && \
    docker-php-ext-configure gd \
        --enable-gd-native-ttf \
        --with-jpeg-dir=/usr/lib \
        --with-freetype-dir=/usr/include/freetype2 && \
    docker-php-ext-install gd
```

Did you notice this `docker-php-ext-install gd` twice? That's wrong I believe correct me if I am wrong

**Comment by Mahmoudz** [comment] 2016-10-10 22:57
@reypm oh yes I do, that comment above was supposed to be for another Issue, sorry about that. Could you confirm that removing any of the lines keeps it running normally? And if so which line should we remove? Cause I can't remove any of them now, since I'm not using that xdebug or php 55, I need a user of them to test it, and let us know what works. You can also submit a PR if you like, otherwise just answer here and I'll do it. Thanks

**Closed** 2017-03-16 18:15 UTC
Labels: Type: Need Help
